### ISSUE TITLE
Error when import css from node_modules

### ISSUE THREAD

**Issue by jiangfengming** [micantoine/svelte-preprocess-cssmodules#10]
## How to reproduce
Import css from node_modules, such as:

```js
import 'swiper/swiper-bundle.css';
```

## Expected
No error

## Actual:
```
[snowpack] Error: Error: ENOENT: no such file or directory, open '/Users/jfm/projects/wscn/app-article-template/src/views/Live/swiper/swiper-bundle.css'
```

**Comment by micantoine** [comment]
@jiangfengming The version `1.3.2` will fix the issue with the style being imported from a *node_modules* package. The preprocess will ignore it as its purpose is to only include relative css modules stylesheets to the svelte component. You will have to set your bundler accordingly (no configuration is required with *snowpack* but the necessary plugins or loaders will have to be added for *rollup* and *webpack*)

I'm thinking to actually use the naming convention `[name].module.css` in a future version to avoid any confusion. It will follow a more standard approach even though the preprocess will keep considering html tag selectors inside the file and import them with the default svelte scoped system.

What do you think ?

**Comment by jiangfengming** [comment]
@micantoine Great!
I actually only used this preprocessor to pass hashed class name to child components. And when I encountered the #5 issue I gave up 😂. As a workaround, I wrote a very simple [preprocessor](https://github.com/jiangfengming/svelte-preprocess-css-hash) to hash the class name inside `:global()` to avoid the unused css selector problem.

> I'm thinking to actually use the naming convention [name].module.css in a future version to avoid any confusion.

I found snowpack officially use this extension, see https://www.snowpack.dev/reference/supported-files#css-modules . So to snowpack users, will this preprocessor bring unexpected behavior?

**Comment by micantoine** [comment]
@jiangfengming you didn't have to give up because of the #5 issue haha. It is just the IDE warning, the preprocessor is working fine.

For snowpack, the preprocessor will behave normally since it is parsing the files first. Interesting point from the [doc]( https://www.snowpack.dev/reference/supported-files#css-modules) though, it seems that snowpack is automatically processing those imported `.module.css` files as cssModules. Basically, if you only use *svelte-preprocess-cssmodules* with external stylesheets containing exclusively classname selectors, you might not need it after all. Snowpack alone would be enough.
