### ISSUE TITLE
Hash identifier

### ISSUE THREAD

**Issue by gwet-stripe** [micantoine/svelte-preprocess-cssmodules#40]
When setting any "mode", Svelte continues to inject a reference hash. How could I simply keep only the style hash without having a reference hash that I don't use.

![image](https://user-images.githubusercontent.com/91576265/148906702-c96e94d7-f07c-470a-a698-1b0adc82be7e.jpeg)

![image](https://user-images.githubusercontent.com/91576265/148906721-5340c8f3-4f2a-4c2e-83be-86c1b4ff83d9.jpeg)

What is really the point of keeping this hash without styles?

**Comment by micantoine** [comment]
Could you give more information about your  settings and component ?
The preprocessor only replaces a classname if it exists in the markup and declared in `style`. The only way I was able to reproduce something similar to what you have was to have an empty class selector on my html tag.

```html
<div class="red empty"></div>

<style module>
.red { color: red }
.empty { }
</style>
```

generating

```html
<div class="red-3NDLpK empty-1Vco_x"></div>

<style>
.red-3NDLpK { color: red }
.empty-1Vco_x { }
</style>
```

**Comment by icui4cu-web** [comment]
I have the same problem
I created a new project according to the documentation
`npm create vite@latest myapp -- --template svelte`
Changed vite.config.js
```
import { defineConfig } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'
import { cssModules } from 'svelte-preprocess-cssmodules'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [svelte({
	preprocess: [
		cssModules(),
	  ]
  })]
})
```
Added "module" to <style>
And got 2 css-classes on tag, from svelte and css-modules plugin
![Снимок экрана от 2022-09-04 19-39-08](https://user-images.githubusercontent.com/104122919/188324088-dbc77e95-479e-4a45-ae76-4c1374014a52.png)

**Comment by micantoine** [comment]
@icui4cu-web thank you for sharing the information.

You are right, the problem is coming from vite.

I ran the default application from `npm create vite@latest myapp -- --template svelte` **without** `cssModules` and all the html tags of the component inherited a scoped class even though no styles were  attached to them.


I also tested the svelte `:global()`
```css
 :global(.read-the-docs) {
    color: #888;
  }
```
and the html element using the class still inherited a scoped class.

<img width="1045" alt="Screen Shot 2022-09-30 at 17 11 40" src="https://user-images.githubusercontent.com/36289018/193224413-0e17d8ce-d8a0-41d5-a35b-a625c583eb95.png">
