### ISSUE TITLE
Trouble using animation/keyframes inside nested components

### ISSUE THREAD

**Issue by iolyd** [micantoine/svelte-preprocess-cssmodules#76]
## Description

Maybe there's something wrong with how I am implementing this, but it seems like animation `@keyframes` are not working when passing a class to a component from within another component. I would say making wrapper components of primitives for reusable behaviors and styles is a common practice, so I would expect other people to have noticed this if it were truly a bug (unless it's already documented somewhere?).

For illustration, I would expect something like this to work consistently:

```html
<!-- Button.svelte -->
<button class="button">
  <slot />
</button>

<style lang="scss">
  .button {
    ...
  }
</style>
```

```html
<!-- ButtonWrapper.svelte -->
<script>
  import Button from './Button.svelte';
  import Icon from './Icon.svelte';
</script>

<Button>
  Some wrapped and slotted content <Icon class="spin" />
</Button>

<style lang="scss" module>
  .spin {
    animation: spin 3s infinite;
  }
  @keyframes spin {...}
</style>
```
But it does not:
```html
<script>
  import Button from './lib/Button.svelte';
  import ButtonWrapper from './lib/ButtonWrapper.svelte';
  import Icon from './lib/Icon.svelte';
</script>

<main>
  <Button>
    Some slotted content <Icon class="spin" />
    <!-- This button's icon is animated, as expected -->
  </Button>
  <ButtonWrapper />
  <!-- This one is not -->
</main>

<style lang="scss" module>
  .spin {
    animation: spin 3s infinite;
  }
  @keyframes spin {...}
</style>

```

Is this a inherent limitation of the preprocessor?

## Repro

https://github.com/iolyd/svelte-cssmodules-preprocess-repro

**Comment by micantoine** [comment]
@iolyd Thank you for the repo, I was able to properly test it.

The issue is coming from the way the keyframes are being scoped and how svelte is cleaning up the styles.

## What's happening
- CssModules only applies to classnames
- Keyframes are using the svelte scoping
- Svelte scoping are meant to be applied to html elements not components. 
- Svelte drops styles if it thinks they are not being used.

### Example 1
```html
<main>
  <Button>
    Some slotted content <Icon class="spin" />
  </Button>
</main>

<style module>
  .spin {
    animation: spin 3s infinite;
  }
  @keyframes spin {...}
</style>
```

**Why it works?**
 The component contains a html tag `main` which will prevent svelte to remove the `keyframes` rule using the svelte scoping.

### Example 2
```html
<Button>
  Some slotted content <Icon class="spin" />
</Button>

<style module>
  .spin {
    animation: spin 3s infinite;
  }
  @keyframes spin {...}
</style>
```

**Why it doesn't works?**
 The component does not contain any html tag. Svelte thinks that the `keyframes` rule cannot be applied and removes it.

## Solution to be worked on
- Stop using svelte scoping on keyframes and apply unique ID with cssModules.

**Comment by micantoine** [comment]
The new release `v2.2.4` is now using cssModules on keyframes
